package dev.kwameopareasiedu.simpson.parser;

import java.util.*;

/**
 * {@link Parser} takes a list of {@link Tokenizer.Token tokens} generated by the {@link Tokenizer} and converts them
 * into a hierarchy of {@link Node} which a consumer can reliably query for data
 */
public class Parser {
  private final Tokenizer.Token[] tokens;
  private int index = 0;
  private int depth = 0;

  /** Creates a new parser from a list of provided {@link Tokenizer.Token tokens} */
  public Parser(Tokenizer.Token[] tokens) {
    if (tokens.length == 0)
      throw new IllegalArgumentException("Token list cannot empty");

    this.tokens = tokens;
  }

  /**
   * Processes the provided {@link Tokenizer.Token tokens} into a {@link Node} hierarchy which is used to extract
   * data from the JSON string the tokens represent.
   */
  public Node<?> parse() {
    depth++;
    Tokenizer.Token currentToken = tokens[index];

    Node<?> parsedNode = switch (currentToken.type()) {
      case STRING -> new StringNode(currentToken.value());
      case INTEGER -> new IntegerNode(Integer.parseInt(currentToken.value()));
      case DECIMAL -> new DecimalNode(Double.parseDouble(currentToken.value()));
      case TRUE -> new BooleanNode(true);
      case FALSE -> new BooleanNode(false);
      case NULL -> new NullNode();
      case BRACE_OPEN -> parseObject();
      case BRACKET_OPEN -> parseArray();
      default -> throw new IllegalArgumentException("Unexpected token: " + currentToken.type());
    };

    depth--;

    if (depth == 0) {
      try {
        Tokenizer.Token nextToken = peek();
        throw new IllegalArgumentException("Unexpected token: " + nextToken.type());
      } catch (IndexOutOfBoundsException ignored) { }
    }

    return parsedNode;
  }

  /** Attempts to parse an {@link ObjectNode} from the current token position onwards */
  private ObjectNode parseObject() {
    Map<String, Node<?>> objectNodeValue = new HashMap<>();
    Tokenizer.Token token = advance(); // Should be an object key

    while (token.type() != Tokenizer.Token.Type.BRACE_CLOSE) {
      if (token.type() == Tokenizer.Token.Type.STRING) {
        String key = token.value();

        token = advance(); // Should be a colon

        if (token.type() != Tokenizer.Token.Type.COLON)
          throw new IllegalArgumentException("Expected : after key");
        else advance();

        Node<?> value = parse();
        objectNodeValue.put(key, value);
      } else {
        throw new IllegalArgumentException(
          "Expected string key in object. Found " + token.type()
        );
      }

      token = advance(); // Should be a comma or a closing brace

      if (token.type() == Tokenizer.Token.Type.COMMA) {
        Tokenizer.Token nextToken = peek();

        // A closing brace should not come immediately after a comma
        if (nextToken.type() == Tokenizer.Token.Type.BRACE_CLOSE) {
          throw new IllegalArgumentException(
            "Expected object key after comma. Found " + nextToken.type()
          );
        }

        token = advance();
        continue;
      }

      if (token.type() != Tokenizer.Token.Type.BRACE_CLOSE)
        throw new IllegalArgumentException(
          "Expected comma after object value. Found " + token.type()
        );
    }

    return new ObjectNode(objectNodeValue);
  }

  /** Attempts to parse an {@link ArrayNode} from the current token position onwards */
  private ArrayNode parseArray() {
    List<Node<?>> arrayNodeValue = new ArrayList<>();
    Tokenizer.Token token = advance(); // Should be an array element

    while (token.type() != Tokenizer.Token.Type.BRACKET_CLOSE) {
      Node<?> value = parse();
      arrayNodeValue.add(value);

      token = advance(); // Should be a comma or a closing bracket

      if (token.type() == Tokenizer.Token.Type.COMMA) {
        Tokenizer.Token nextToken = peek();

        // A closing bracket should not come immediately after a comma
        if (nextToken.type() == Tokenizer.Token.Type.BRACKET_CLOSE) {
          throw new IllegalArgumentException(
            "Expected array element after comma. Found " + nextToken.type()
          );
        }

        token = advance();
        continue;
      }

      if (token.type() != Tokenizer.Token.Type.BRACKET_CLOSE)
        throw new IllegalArgumentException(
          "Expected comma after array element. Found " + token.type()
        );
    }

    return new ArrayNode(arrayNodeValue.toArray(Node[]::new));
  }

  /** Advances the internal token index and returns the token at the new index */
  private Tokenizer.Token advance() {
    return tokens[++index];
  }

  /** Returns the token at the next index without modifying the index */
  private Tokenizer.Token peek() {
    return tokens[index + 1];
  }

  /** {@link Node} forms the base of parsed structures from a valid JSON string */
  public static abstract class Node<V> {
    protected final Type type;
    protected final V value;

    /** Creates a new {@link Node} of the specified {@link Type type} and value */
    protected Node(Type type, V value) {
      this.type = type;
      this.value = value;
    }

    /** Returns the value of this node */
    public V get() {
      return value;
    }

    /** Returns {@code true} if this node is a {@link StringNode} and false otherwise */
    public boolean isString() {
      return type == Node.Type.STRING;
    }

    /** Returns {@code true} if this node is an {@link IntegerNode} and false otherwise */
    public boolean isInteger() {
      return type == Node.Type.INTEGER;
    }

    /** Returns {@code true} if this node is a {@link DecimalNode} and false otherwise */
    public boolean isDecimal() {
      return type == Node.Type.DECIMAL;
    }

    /** Returns {@code true} if this node is a {@link BooleanNode} and false otherwise */
    public boolean isBoolean() {
      return type == Node.Type.BOOLEAN;
    }

    /** Returns {@code true} if this node is a {@link ObjectNode} and false otherwise */
    public boolean isObject() {
      return type == Node.Type.OBJECT;
    }

    /** Returns {@code true} if this node is a {@link ArrayNode} and false otherwise */
    public boolean isArray() {
      return type == Node.Type.ARRAY;
    }

    /** Returns {@code true} if this node is a {@link NullNode} and false otherwise */
    public boolean isNull() {
      return type == Node.Type.NULL;
    }

    @Override
    public String toString() {
      return String.format("%s[%s]", getClass().getSimpleName(), value);
    }

    /** Represents a valid {@link Node} type */
    public enum Type {
      STRING,
      INTEGER,
      DECIMAL,
      BOOLEAN,
      OBJECT,
      ARRAY,
      NULL,
    }
  }

  /** {@link StringNode} is a {@link Node} whose value is a string */
  public static class StringNode extends Node<String> {
    protected StringNode(String value) {
      super(Type.STRING, value);
    }
  }

  /** {@link IntegerNode} is a {@link Node} whose value is an integer */
  public static class IntegerNode extends Node<Integer> {
    protected IntegerNode(Integer value) {
      super(Type.INTEGER, value);
    }
  }

  /** {@link DecimalNode} is a {@link Node} whose value is a double */
  public static class DecimalNode extends Node<Double> {
    protected DecimalNode(Double value) {
      super(Type.DECIMAL, value);
    }
  }

  /** {@link BooleanNode} is a {@link Node} whose value is a boolean */
  public static class BooleanNode extends Node<Boolean> {
    protected BooleanNode(boolean value) {
      super(Type.BOOLEAN, value);
    }
  }

  /** {@link ObjectNode} is a {@link Node} whose value is a map of string keys to other {@link Node nodes} */
  public static class ObjectNode extends Node<Map<String, Node<?>>> {
    protected ObjectNode(Map<String, Node<?>> value) {
      super(Type.OBJECT, value);
    }

    /** Checks if this node's map has the specified key */
    public boolean has(String key) {
      return value.containsKey(key);
    }

    /**
     * Returns the node in the value map matching the given key.
     * <p>
     * The key can be a simple key or a dot-notation representing a path within the value map.
     * <p>
     * As an example, let's say this {@link ObjectNode} is parsed from the following JSON string:
     * <pre>
     * {@code
     * {
     *   "id": "647ceaf3657eade56f8224eb",
     *   "index": 0,
     *   "double": 0.13,
     *   "array": [
     *     1,
     *     "another",
     *     true,
     *     false,
     *     { "foo": "bar" },
     *     [],
     *     [1, 2, "hello"]
     *   ],
     *   "booleanTrue": true,
     *   "booleanFalse": false,
     *   "null": null
     * }
     * }
     * </pre>
     * <p>
     * The output of the following would result in:
     * <pre>
     * {@code
     * Parser.ObjectNode parsed = (Parser.ObjectNode) Simpson.parse(objectJson);
     *
     * System.out.println(parsed.get("id"));                   // StringNode[647ceaf3657eade56f8224eb]
     * System.out.println(parsed.get("id").get());             // 647ceaf3657eade56f8224eb
     * System.out.println(parsed.get("index"));                // IntegerNode[0]
     * System.out.println(parsed.get("index").isInteger());    // true
     * System.out.println(parsed.get("double"));               // DoubleNode[0.13]
     * System.out.println(parsed.get("array.4.foo"));          // StringNode[bar]
     * System.out.println(parsed.get("array.5.2"));            // StringNode[hello]
     * }
     * </pre>
     * <p>
     * As shows in the last two outputs, to retrieve an inner member, you pass the dot-notation path to this method.
     * Each part of the dot-notation path is either an object key or an array index.
     */
    public Node<?> get(String keyOrPath) {
      Node<?> node = value.get(keyOrPath);
      if (node != null) return node;

      // Parse as path string (E.g. "nested.items.0.attribute")
      String[] parts = keyOrPath.split("\\.");
      Node<?> nextNode = null;
      int index = 0;

      while (index < parts.length) {
        String nextKey = parts[index];

        if (nextNode == null) {
          nextNode = value.get(nextKey);
        } else if (nextNode instanceof ObjectNode) {
          nextNode = ((ObjectNode) nextNode).get(nextKey);
        } else if (nextNode instanceof ArrayNode) {
          nextNode = ((ArrayNode) nextNode).get(Integer.parseInt(nextKey));
        }

        index++;
      }

      return nextNode;
    }

    /**
     * Returns the {@link StringNode} with the specified key.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link StringNode}
     */
    public StringNode getStringNode(String keyOrPath) throws ClassCastException {
      return (StringNode) get(keyOrPath);
    }

    /**
     * Returns the {@link IntegerNode} with the specified key.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link IntegerNode}
     */
    public IntegerNode getIntegerNode(String keyOrPath) throws ClassCastException {
      return (IntegerNode) get(keyOrPath);
    }

    /**
     * Returns the {@link DecimalNode} with the specified key.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link DecimalNode}
     */
    public DecimalNode getDecimalNode(String keyOrPath) throws ClassCastException {
      return (DecimalNode) get(keyOrPath);
    }

    /**
     * Returns the {@link BooleanNode} with the specified key.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link BooleanNode}
     */
    public BooleanNode getBooleanNode(String keyOrPath) throws ClassCastException {
      return (BooleanNode) get(keyOrPath);
    }

    /**
     * Returns the {@link ObjectNode} with the specified key.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link ObjectNode}
     */
    public ObjectNode getObjectNode(String keyOrPath) throws ClassCastException {
      return (ObjectNode) get(keyOrPath);
    }

    /**
     * Returns the {@link ArrayNode} with the specified key.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link ArrayNode}
     */
    public ArrayNode getArrayNode(String keyOrPath) throws ClassCastException {
      return (ArrayNode) get(keyOrPath);
    }

    /**
     * Returns the {@link NullNode} with the specified key.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link NullNode}
     */
    public NullNode getNullNode(String keyOrPath) throws ClassCastException {
      return (NullNode) get(keyOrPath);
    }

    @Override
    public String toString() {
      StringBuilder builder = new StringBuilder("ObjectNode[");

      Set<Map.Entry<String, Node<?>>> entries = value.entrySet();
      int index = 0;

      for (Map.Entry<String, Node<?>> pair : entries) {
        builder.append(pair.getKey());
        builder.append("=");
        builder.append(pair.getValue().toString());

        if (index < entries.size() - 1)
          builder.append(", ");

        index++;
      }

      builder.append("]");
      return builder.toString();
    }
  }

  /** {@link ArrayNode} is a {@link Node} whose value is an array other {@link Node nodes} */
  public static class ArrayNode extends Node<Node<?>[]> {
    protected ArrayNode(Node<?>[] value) {
      super(Type.ARRAY, value);
    }

    /** Returns the length of the node array */
    public int getLength() {
      return value.length;
    }

    /**
     * Returns the node in the value array at the given index
     *
     * @throws IndexOutOfBoundsException if the index is out of bounds
     */
    public Node<?> get(int index) throws IndexOutOfBoundsException {
      if (index < 0 || index >= value.length)
        throw new IndexOutOfBoundsException(index);

      return value[index];
    }

    /**
     * Returns the {@link StringNode} at the given index.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link StringNode}
     */
    public StringNode getStringNode(int index) throws ClassCastException {
      return (StringNode) get(index);
    }

    /**
     * Returns the {@link IntegerNode} at the given index.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link IntegerNode}
     */
    public IntegerNode getIntegerNode(int index) throws ClassCastException {
      return (IntegerNode) get(index);
    }

    /**
     * Returns the {@link DecimalNode} at the given index.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link DecimalNode}
     */
    public DecimalNode getDecimalNode(int index) throws ClassCastException {
      return (DecimalNode) get(index);
    }

    /**
     * Returns the {@link BooleanNode} at the given index.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link BooleanNode}
     */
    public BooleanNode getBooleanNode(int index) throws ClassCastException {
      return (BooleanNode) get(index);
    }

    /**
     * Returns the {@link ObjectNode} at the given index.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link ObjectNode}
     */
    public ObjectNode getObjectNode(int index) throws ClassCastException {
      return (ObjectNode) get(index);
    }

    /**
     * Returns the {@link ArrayNode} at the given index.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link ArrayNode}
     */
    public ArrayNode getArrayNode(int index) throws ClassCastException {
      return (ArrayNode) get(index);
    }

    /**
     * Returns the {@link NullNode} at the given index.
     *
     * @throws ClassCastException if the target node cannot be cast into a {@link NullNode}
     */
    public NullNode getNullNode(int index) throws ClassCastException {
      return (NullNode) get(index);
    }

    @Override
    public String toString() {
      StringBuilder builder = new StringBuilder("ArrayNode[");

      for (int index = 0; index < value.length; index++) {
        builder.append(value[index].toString());

        if (index < value.length - 1)
          builder.append(", ");
      }

      builder.append("]");
      return builder.toString();
    }
  }

  /** {@link NullNode} is a {@link Node} whose value {@code null} */
  public static class NullNode extends Node<Object> {
    protected NullNode() {
      super(Type.NULL, null);
    }
  }
}
