package dev.kwameopareasiedu.simpson;

import dev.kwameopareasiedu.simpson.nodes.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * {@link Parser} takes a list of {@link Token tokens} generated by the {@link Tokenizer} and converts them
 * into a hierarchy of {@link Node} which a consumer can reliably query for data
 */
public class Parser {
  private final Token[] tokens;
  private int index = 0;
  private int depth = 0;

  /** Creates a new parser from a list of provided {@link Token tokens} */
  public Parser(Token[] tokens) {
    if (tokens.length == 0)
      throw new IllegalArgumentException("Token list cannot empty");

    this.tokens = tokens;
  }

  /**
   * Processes the provided {@link Token tokens} into a {@link Node} hierarchy which is used to extract
   * data from the JSON string the tokens represent.
   */
  public Node<?> parse() {
    depth++;
    Token currentToken = tokens[index];

    Node<?> parsedNode = switch (currentToken.type()) {
      case STRING -> new StringNode(currentToken.value());
      case INTEGER -> new IntegerNode(Integer.parseInt(currentToken.value()));
      case DECIMAL -> new DecimalNode(Double.parseDouble(currentToken.value()));
      case TRUE -> new BooleanNode(true);
      case FALSE -> new BooleanNode(false);
      case NULL -> new NullNode();
      case BRACE_OPEN -> parseObject();
      case BRACKET_OPEN -> parseArray();
      default -> throw new IllegalArgumentException("Unexpected token: " + currentToken.type());
    };

    depth--;

    if (depth == 0) {
      try {
        Token nextToken = peek();
        throw new IllegalArgumentException("Unexpected token: " + nextToken.type());
      } catch (IndexOutOfBoundsException ignored) { }
    }

    return parsedNode;
  }

  /** Attempts to parse an {@link ObjectNode} from the current token position onwards */
  private ObjectNode parseObject() {
    Map<String, Node<?>> objectNodeValue = new HashMap<>();
    Token token = advance(); // Should be an object key

    while (token.type() != Token.Type.BRACE_CLOSE) {
      if (token.type() == Token.Type.STRING) {
        String key = token.value();

        token = advance(); // Should be a colon

        if (token.type() != Token.Type.COLON)
          throw new IllegalArgumentException("Expected : after key");
        else advance();

        Node<?> value = parse();
        objectNodeValue.put(key, value);
      } else {
        throw new IllegalArgumentException(
          "Expected string key in object. Found " + token.type()
        );
      }

      token = advance(); // Should be a comma or a closing brace

      if (token.type() == Token.Type.COMMA) {
        Token nextToken = peek();

        // A closing brace should not come immediately after a comma
        if (nextToken.type() == Token.Type.BRACE_CLOSE) {
          throw new IllegalArgumentException(
            "Expected object key after comma. Found " + nextToken.type()
          );
        }

        token = advance();
        continue;
      }

      if (token.type() != Token.Type.BRACE_CLOSE)
        throw new IllegalArgumentException(
          "Expected comma after object value. Found " + token.type()
        );
    }

    return new ObjectNode(objectNodeValue);
  }

  /** Attempts to parse an {@link ArrayNode} from the current token position onwards */
  private ArrayNode parseArray() {
    List<Node<?>> arrayNodeValue = new ArrayList<>();
    Token token = advance(); // Should be an array element

    while (token.type() != Token.Type.BRACKET_CLOSE) {
      Node<?> value = parse();
      arrayNodeValue.add(value);

      token = advance(); // Should be a comma or a closing bracket

      if (token.type() == Token.Type.COMMA) {
        Token nextToken = peek();

        // A closing bracket should not come immediately after a comma
        if (nextToken.type() == Token.Type.BRACKET_CLOSE) {
          throw new IllegalArgumentException(
            "Expected array element after comma. Found " + nextToken.type()
          );
        }

        token = advance();
        continue;
      }

      if (token.type() != Token.Type.BRACKET_CLOSE)
        throw new IllegalArgumentException(
          "Expected comma after array element. Found " + token.type()
        );
    }

    return new ArrayNode(arrayNodeValue.toArray(Node[]::new));
  }

  /** Advances the internal token index and returns the token at the new index */
  private Token advance() {
    return tokens[++index];
  }

  /** Returns the token at the next index without modifying the index */
  private Token peek() {
    return tokens[index + 1];
  }
}
